/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.add;

import BUS.SanPhamBUS;
import DTO.SanPhamDTO;
import BUS.PhieuXuatBUS;
import DTO.PhieuXuatDTO;
import BUS.GiamGiaBUS;
import DTO.GiamGiaDTO;
import BUS.KhachHangBUS;
import BUS.LoHangBUS;
import DTO.KhachHangDTO;
import BUS.NhanVienBUS;
import DTO.LoHangDTO;
import DTO.NhanVienDTO;
import GUI.login;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NeON
 */
public class addphieuxuat extends javax.swing.JPanel {

    ArrayList<SanPhamDTO> list = new ArrayList<SanPhamDTO>();
    ArrayList<NhanVienDTO> listTennv = new ArrayList<NhanVienDTO>();
    SanPhamBUS spBUS = new SanPhamBUS();
    PhieuXuatBUS pxBUS = new PhieuXuatBUS();
    GiamGiaBUS ggBUS = new GiamGiaBUS();
    KhachHangBUS khBUS = new KhachHangBUS();
    NhanVienBUS nvBUS = new NhanVienBUS();
    LoHangBUS lhBUS = new LoHangBUS();

    int current = 0;

    public addphieuxuat() {
        initComponents();

        combohotenDisplay();
        listTennv = nvBUS.nvDAO.selectAll();
        displaytoTxttennvxuat(listTennv);
        list = spBUS.spDAO.selectAll();
        displaytoTable1(list);

        txtsdt.setEditable(false);
        txtdiachi.setEditable(false);
        txttennvxuat.setEditable(false);
        tblphieuxuatin.setDefaultEditor(Object.class, null);
        tblphieuxuatout.setDefaultEditor(Object.class, null);
    }

    private void displaytoTable1(ArrayList<SanPhamDTO> list) {
        try {
            DefaultTableModel dt = (DefaultTableModel) tblphieuxuatin.getModel();
            dt.setRowCount(0);
            for (SanPhamDTO i : list) {
                if (i.getSoluongton() >= 1) {
                    dt.addRow(new Object[]{
                        i.getMasp(), i.getTensp(), i.getSoluongton(), i.getGia()
                    });
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void combohotenDisplay() {
        ArrayList<KhachHangDTO> listkh = khBUS.khDAO.selectAll();
        for (KhachHangDTO kh : listkh) {
            combohoten.addItem(kh.getHoten());
        }
    }

    private void displaytoTxttennvxuat(ArrayList<NhanVienDTO> listTennv) {
        for (NhanVienDTO j : listTennv) {
            if (login.t.getMaaccount() == j.getManv()) {
                txttennvxuat.setText("" + j.getHoten());
                break;
            }
        }
    }

    /**
     * fo This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblphieuxuatin = new javax.swing.JTable();
        btnthemsp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txttennvxuat = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnxuatphieu = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        combohoten = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblphieuxuatout = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblphieuxuatin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Giá bán"
            }
        ));
        tblphieuxuatin.setRowHeight(50);
        jScrollPane2.setViewportView(tblphieuxuatin);

        btnthemsp.setBackground(new java.awt.Color(102, 204, 0));
        btnthemsp.setForeground(new java.awt.Color(255, 255, 255));
        btnthemsp.setText("Thêm");
        btnthemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemspActionPerformed(evt);
            }
        });

        jLabel12.setText("Nhân viên xuất");

        jLabel17.setText("Số lượng");

        txttennvxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttennvxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttennvxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnthemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttennvxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnxuatphieu.setBackground(new java.awt.Color(102, 204, 0));
        btnxuatphieu.setForeground(new java.awt.Color(255, 255, 255));
        btnxuatphieu.setText("Xuất phiếu");
        btnxuatphieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatphieuActionPerformed(evt);
            }
        });

        jLabel13.setText("Họ tên KH");

        jLabel14.setText("Số ĐT");

        jLabel15.setText("Địa chỉ");

        combohoten.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combohotenItemStateChanged(evt);
            }
        });

        tblphieuxuatout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Giá"
            }
        ));
        tblphieuxuatout.setRowHeight(50);
        tblphieuxuatout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblphieuxuatoutMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblphieuxuatout);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnxuatphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(combohoten, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtdiachi)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combohoten))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnxuatphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combohotenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combohotenItemStateChanged
        // TODO add your handling code here:
        ArrayList<KhachHangDTO> listkh = khBUS.khDAO.selectAll();
        for (KhachHangDTO i : listkh) {
            if (("" + i.getHoten()).equalsIgnoreCase((String) combohoten.getSelectedItem())) {
                txtsdt.setText("" + i.getSdt());
                txtdiachi.setText("" + i.getDiachi());
            }
        }
    }//GEN-LAST:event_combohotenItemStateChanged

    private void btnthemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemspActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblphieuxuatin.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm từ bảng 1.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy dữ liệu sản phẩm từ dòng được chọn
        Object[] rowData = new Object[4];
        for (int i = 0; i < 4; i++) {
            rowData[i] = tblphieuxuatin.getValueAt(selectedRow, i);
        }

        // Lấy số lượng nhập
        int soluong;
        try {
            soluong = Integer.parseInt(txtsoluong.getText().trim());
            if (soluong <= 0 || soluong > Integer.parseInt(rowData[2].toString())) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Trừ đi số lượng đã lấy
        tblphieuxuatin.setValueAt(Integer.parseInt(rowData[2].toString()) - soluong, selectedRow, 2);

        // Kiểm tra đã có sản phẩm ở bảng 2 chưa
        int check = 1;
        DefaultTableModel dt2 = (DefaultTableModel) tblphieuxuatout.getModel();
        for (int row = 0; row < dt2.getRowCount(); row++) {
            if (dt2.getValueAt(row, 0) == rowData[0]) {
                // Cộng thêm
                dt2.setValueAt(Integer.parseInt(dt2.getValueAt(row, 2).toString()) + soluong, row, 2);
                check = 0;
            }
        }
        if (check == 1) {
            // Thêm thông tin sản phẩm vào bảng 2
            rowData[2] = soluong; // Cập nhật số lượng
            dt2.addRow(rowData);
            
        }

        // Xóa số lượng đã nhập
        txtsoluong.setText("");
    }//GEN-LAST:event_btnthemspActionPerformed

    private void btnxuatphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatphieuActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) tblphieuxuatout.getModel();
          
           
            if (model.getRowCount() <= 0) {
                // Hiển thị thông báo chưa chọn sản phẩm
                JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ArrayList<NhanVienDTO> listnv = nvBUS.getAll();
            ArrayList<KhachHangDTO> listkh = khBUS.getAll();
            ArrayList<LoHangDTO> listlh = lhBUS.getAll();

            int rowCount = model.getRowCount();

            Date thoigian = new Date(System.currentTimeMillis());
            java.sql.Date sqlDate = new java.sql.Date(thoigian.getTime());
            long tongtien = 0;
            int sumsoluong = 0;
            int mapx = pxBUS.phieuXuatDAO.getAutoIncrement();
            String tennv = "" + txttennvxuat.getText();
            int manv = 1;
            for (NhanVienDTO i : listnv) {
                if (tennv.equalsIgnoreCase(i.getHoten())) {
                    manv = i.getManv();
                    break;
                }
            }
            int makh = 1;
            String tenkh = "" + combohoten.getSelectedItem();
            for (KhachHangDTO i : listkh) {
                if (tenkh.equalsIgnoreCase(i.getHoten())) {
                    makh = i.getMaKH();
                    break;
                }
            }

            PhieuXuatDTO pxAll = new PhieuXuatDTO(mapx, sqlDate, tongtien, sumsoluong, manv, makh);
            pxBUS.phieuXuatDAO.insert(pxAll);

            // Lặp qua các dòng trong bảng 2 (tblphieuxuatout)
            for (int i = 0; i < rowCount; i++) {
                // Lấy mã sản phẩm và số lượng từ bảng 2
                int masp = (int) model.getValueAt(i, 0);
                int soluong = (int) model.getValueAt(i, 2);
                int dongia = (int) model.getValueAt(i, 3);
                tongtien += soluong * dongia;

                // Thêm chi tiết phiếu xuất
                PhieuXuatDTO ctpx = new PhieuXuatDTO(mapx, masp, soluong, dongia);
                pxBUS.phieuXuatDAO.insertCtpx(ctpx);

                // Trừ số lượng sản phẩm theo mã phiếu nhập nhỏ hơn trước
                ArrayList<LoHangDTO> danhSachSanPham = new ArrayList<>();
                for (LoHangDTO loHang : listlh) {
                    if (loHang.getMasp() == masp) {
                        danhSachSanPham.add(loHang);
                    }
                }

                // Sắp xếp danh sách theo mã phiếu nhập tăng dần
                Collections.sort(danhSachSanPham, Comparator.comparing(LoHangDTO::getMaphieunhap));

                // Thực hiện trừ số lượng từ danh sách sản phẩm
                for (LoHangDTO loHang : danhSachSanPham) {
                    if (soluong <= 0) {
                        break;
                    }

                    int soLuongHienTai = loHang.getSoluong();
                    if (soLuongHienTai <= soluong) {
                        soluong -= soLuongHienTai;
                        loHang.setSoluong(0);

                        // Cập nhật số lượng của lô hàng trong CSDL
                        lhBUS.lhDAO.updateQuantity(loHang.getMaphieunhap(), 0);
                    } else {
                        loHang.setSoluong(soLuongHienTai - soluong);
                        lhBUS.lhDAO.updateQuantity(loHang.getMaphieunhap(), loHang.getSoluong());
                        soluong = 0;
                    }
                }

                // Kiểm tra và xóa các mã phiếu nhập có số lượng = 0
                for (LoHangDTO loHang : danhSachSanPham) {
                    if (loHang.getSoluong() == 0) {
                        lhBUS.lhDAO.delete(loHang.getMaphieunhap());
                    }
                }

                // Cập nhật sản phẩm
                boolean spUpdateSuccess = spBUS.subtractQuantity(masp, soluong);
            }

            pxAll = new PhieuXuatDTO(mapx, sqlDate, tongtien, sumsoluong, manv, makh);
            pxBUS.phieuXuatDAO.update(pxAll);
            // Reset bảng 2 (tblphieuxuatout)
            model.setRowCount(0);

            // Hiển thị thông báo thành công
            JOptionPane.showMessageDialog(this, "Nhập hàng thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cập nhật không thành công.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        displaytoTable1(spBUS.spDAO.selectAll());
    }//GEN-LAST:event_btnxuatphieuActionPerformed
 
    
    private void txttennvxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttennvxuatActionPerformed
        
    }//GEN-LAST:event_txttennvxuatActionPerformed

    private void tblphieuxuatoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphieuxuatoutMouseClicked
   
    
    }//GEN-LAST:event_tblphieuxuatoutMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthemsp;
    private javax.swing.JButton btnxuatphieu;
    private javax.swing.JComboBox<String> combohoten;
    private javax.swing.ButtonGroup groupGioiTinh;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblphieuxuatin;
    private javax.swing.JTable tblphieuxuatout;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttennvxuat;
    // End of variables declaration//GEN-END:variables
}
